name: Deploy & Upload Plugin

on:
  release:
    types:
      - published
      - prereleased

jobs:
  download:
    name: Download Latest Plugin JAR
    runs-on: ubuntu-latest

    steps:
      - name: Download latest release jar
        run: |
          # get latest release info
          ASSET_INFO=$(curl -s -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.tag_name }} \
            | jq -r '.assets[] | select(.name | endswith(".jar")) | "\(.name)|\(.browser_download_url)"')
          
          NAME=$(echo "$ASSET_INFO" | cut -d'|' -f1)
          URL=$(echo "$ASSET_INFO" | cut -d'|' -f2)
          
          echo "Downloading $NAME from $URL"
          curl -L -o "$NAME" "$URL"
          
          echo "JAR_NAME=$NAME" >> $GITHUB_ENV
    

  modrinth:
    name: Upload to Modrinth
    runs-on: ubuntu-latest
    needs: download
    if: false # skip until we have modrinth approval

    steps:
      - name: Publish to Modrinth
        if: false # skip for now
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MR_TOKEN }}
          project: ${{ env.MR_PRJID }}
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          # channel: alpha
          game-versions: |-
            1.21.x
          # if we test/support more, add them here
          # 1.20.6
          # 26.1.x
          loaders: |-
            paper
            spigot
            bukkit
          files: |-
            build/libs/*.jar
          dependencies: |- 
            [{
              "project_id": "8hfcZ97y",
              "dependency_type": "required"
            }]


  spigotmc:
    name: Upload to SpigotMC Resources
    runs-on: ubuntu-latest
    needs: download
    if: false # skip until we figure this out

  hangar:
    name: Upload to PaperMC Hangar
    runs-on: ubuntu-latest
    needs: download
    if: false # skip until configured

  test_server:
    name: Deploy to Test Server
    runs-on: ubuntu-latest
    needs: download

    steps:
      - name: Stop server
        run: |
          curl --request POST \
            --url '${{ env.PANEL_CLIENT_API }}/servers/${{ env.PANEL_SERVER_ID }}/power' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "signal": "stop"
          }'

      - name: Remove old versions
        run: |
          curl --request POST \
            --url '${{ env.PANEL_CLIENT_API }}/servers/${{ env.PANEL_SERVER_ID }}/files/delete' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "root": "plugins",
            "files": [
              "SocialCredit-StupidAddon-*.jar"
            ]
          }'

      - name: Get upload URL
        run: |
          url=$(curl --request GET \
            --url '${{ env.PANEL_CLIENT_API }}/servers/${{ env.PANEL_SERVER_ID }}/files/upload' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' |
          | jq -r '.attributes.url')

          echo "SIGNED_URL=$url" >> $GITHUB_ENV

      - name: Upload plugin to panel
        run: |
          # get jar name  
          # JAR=$(ls *.jar | head -n 1)

          curl --request POST \
            --url '${{ env.SIGNED_URL }}' \
            -F "file=@${{ env.JAR_NAME }}" \
            -F "directory=plugins"

      - name: Start server
        run: |
          curl --request POST \
            --url '${{ env.PANEL_CLIENT_API }}/servers/${{ env.PANEL_SERVER_ID }}/power' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "signal": "start"
          }'



