name: Deploy & Upload Plugin

on:
  release:
    types:
      - published

jobs:
  modrinth:
    name: Upload to Modrinth
    runs-on: ubuntu-latest

    steps:
      - name: Download plugin JAR
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.jar'

      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MR_TOKEN }}
          project: ${{ env.MR_PRJID }}
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          # channel: alpha
          game-versions: |-
            1.21.x
            1.20.6
          # if we test/support more, add them here
          # 1.20.6
          # 26.1.x
          loaders: |-
            paper
            spigot
            bukkit
          files: |-
            *.jar
          dependencies: |- 
            [{
              "project_id": "8hfcZ97y",
              "dependency_type": "required"
            }]


  hangar:
    name: Upload to PaperMC Hangar
    runs-on: ubuntu-latest

    steps:
      - name: Download plugin JAR
        id: download
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.jar'

      - name: Upload to Hangar
        uses: benwoo1110/hangar-upload-action@v1
        with:
          api_token: ${{ secrets.HANGAR_TOKEN }}
          slug: 'SocialCredit-StupidAddon'
          version: ${{ github.event.release.tag_name }}
          channel: release
          files: |
            [
              {
                "path": " ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}",
                "platforms": ["PAPER"]
              }
            ]
          platform_dependencies: |
            {
              "PAPER": ["1.20.6", "1.21.x"]
            }
          plugin_dependencies: |
            [
              {
                "name": "SocialCredit",
                "required": true,
                "externalUrl": "https://github.com/ZeeRaider/SocialCredit"
              }
            ]

  test_server:
    name: Deploy to Test Server
    runs-on: ubuntu-latest

    steps:
      - name: Download plugin JAR
        id: download
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.jar'

      - name: Stop server
        run: |
          curl --request POST \
            --url '${{ env.PANEL_CLIENT_API }}/servers/${{ env.PANEL_SERVER_ID }}/power' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "signal": "stop"
          }'

      - name: Remove old versions
        run: |
          curl --request POST \
            --url '${{ env.PANEL_CLIENT_API }}/servers/${{ env.PANEL_SERVER_ID }}/files/delete' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "root": "plugins",
            "files": [
              "SocialCredit-StupidAddon-*.jar"
            ]
          }'

      - name: Get upload URL
        run: |
          url=$(curl --request GET \
            --url '${{ env.PANEL_CLIENT_API }}/servers/${{ env.PANEL_SERVER_ID }}/files/upload' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
          | jq -r '.attributes.url')

          echo "SIGNED_URL=$url" >> $GITHUB_ENV

      - name: Upload plugin to panel
        run: |
          # get jar name  
          # JAR=$(ls *.jar | head -n 1)

          curl --request POST \
            --url '${{ env.SIGNED_URL }}' \
            -F "file=@${{ fromJson(steps.download.outputs.downloaded_files)[0] }}" \
            -F "directory=plugins"

      - name: Start server
        run: |
          curl --request POST \
            --url '${{ env.PANEL_CLIENT_API }}/servers/${{ env.PANEL_SERVER_ID }}/power' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "signal": "start"
          }'



