name: Deploy & Upload Plugin

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v0.3)'
        required: true

jobs:
  setup:
    name: Setup Release Info
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set.outputs.tag }}
      version: ${{ steps.set.outputs.version }}
      name: ${{ steps.set.outputs.name }}
      changelog: ${{ steps.set.outputs.changelog }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # need all tags

      - name: Determine release info
        id: set
        run: |
          # get tag from input or release event
          TAG="${{ inputs.tag || github.event.release.tag_name }}"
          echo "TAG=$TAG"
          
          # version same as tag
          VERSION="$TAG"
          
          # release name
          NAME="${{ inputs.name || github.event.release.name }}"
          if [ -z "$NAME" ]; then
            NAME=$(git log -1 --pretty=%s $TAG)
          fi
          
          # changelog
          BODY="${{ inputs.changelog || github.event.release.body }}"
          if [ -z "$BODY" ]; then
            BODY=$(git log -1 --pretty=%B $TAG)
          fi
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "changelog=$BODY" >> $GITHUB_OUTPUT
          

  modrinth:
    name: Upload to Modrinth
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Download plugin JAR
        id: download
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.jar'
          out-file-path: '.'

      - name: Move downloaded JAR to workspace root
        run: |
          FILE="${{ fromJson(steps.download.outputs.downloaded_files)[0] }}"
          BASENAME=$(basename "$FILE")
          echo "JAR_NAME=$BASENAME" >> $GITHUB_ENV

      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MR_TOKEN }}
          project: ${{ vars.MR_PRJID }}
          name: ${{ steps.download.outputs.release_name }}
          version: ${{ steps.download.outputs.tag_name }}
          changelog: ${{ needs.setup.outputs.changelog }}
          # channel: alpha
          game-versions: |-
            1.21.x
            1.20.6
          # if we test/support more, add them here
          # 1.20.6
          # 26.1.x
          loaders: |-
            paper
            spigot
            bukkit
            purpur
          files: |-
            ${{ env.JAR_NAME }}
          dependencies: |- 
            [{
              "project_id": "8hfcZ97y",
              "dependency_type": "required"
            }]


  hangar:
    name: Upload to PaperMC Hangar
    runs-on: ubuntu-latest
    if: false # doesn't work
    needs: setup

    steps:
      - name: Get plugin JAR URL
        id: url
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          url=$(gh release view ${{ needs.setup.outputs.tag }} --repo ${{ github.repository }} \
            --json assets | jq '.assets[] | .url')
          echo "JAR_URL=$url" >> $GITHUB_ENV

      - name: Upload to Hangar
        uses: benwoo1110/hangar-upload-action@v1
        with:
          api_token: ${{ secrets.HANGAR_TOKEN }}
          slug: 'SocialCredit-StupidAddon'
          version: ${{ needs.setup.outputs.tag }}
          channel: release
          files: |
            [
              {
                "url": true,
                "externalUrl": ${{ env.JAR_URL }},
                "platforms": ["PAPER"]
              }
            ]
          platform_dependencies: |
            {
              "PAPER": ["1.20.6", "1.21.x"]
            }
          plugin_dependencies: |
            [
              {
                "name": "SocialCredit",
                "required": true,
                "externalUrl": "https://github.com/ZeeRaider/SocialCredit"
              }
            ]

  test_server:
    name: Deploy to Test Server
    runs-on: ubuntu-latest
    if: false # doesn't even work cuz of cloudflare uggghhhhh
    needs: setup

    steps:
      - name: Download plugin JAR
        id: download
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.jar'
          out-file-path: '.'

      - run: ls -R .

      - name: Stop server
        run: |
          curl --request POST \
            --url '${{  vars.PANEL_CLIENT_API }}/servers/${{ vars.PANEL_SERVER_ID }}/power' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "signal": "stop"
          }'

      - name: Remove old versions
        run: |
          curl --request POST \
            --url '${{ vars.PANEL_CLIENT_API }}/servers/${{ vars.PANEL_SERVER_ID }}/files/delete' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "root": "plugins",
            "files": [
              "SocialCredit-StupidAddon-*.jar"
            ]
          }'

      - name: Get upload URL
        run: |
          url=$(curl --request GET \
            --url '${{ vars.PANEL_CLIENT_API }}/servers/${{ vars.PANEL_SERVER_ID }}/files/upload' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
          | jq -r '.attributes.url')
          
          echo "Response: $url"

          echo "SIGNED_URL=$url" >> $GITHUB_ENV

      - name: Upload plugin to panel
        run: |
          # get jar name  
          # JAR=$(ls *.jar | head -n 1)

          curl --request POST \
            --url '${{ env.SIGNED_URL }}' \
            -F "file=@${{ fromJson(steps.download.outputs.downloaded_files)[0] }}" \
            -F "directory=plugins"

      - name: Start server
        run: |
          curl --request POST \
            --url '${{ vars.PANEL_CLIENT_API }}/servers/${{ vars.PANEL_SERVER_ID }}/power' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer ${{ secrets.PANEL_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "signal": "start"
          }'



