name: Generate Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Plugin JAR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          GPR_USER: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Keep only shadow JAR
        run: |
          # delete non-all jars
          find build/libs -type f -name "*.jar" ! -name "*-all.jar" -delete
          # rename -all.jar to normal
          shopt -s nullglob
          for f in build/libs/*-all.jar; do
            mv "$f" "${f%-all.jar}.jar"
          done

      - name: Upload artefact
        uses: actions/upload-artifact@v7
        with:
          path: build/libs/*.jar

  release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write
      actions: read

    steps:
      - uses: actions/checkout@v6

      - run: mkdir -p download

      - name: Download artefact
        uses: actions/download-artifact@v8
        with:
          path: download

      - name: Get tag message
        id: tagmsg
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}

          # get tag message (annotated tag)
          TAG_MESSAGE=$(git for-each-ref refs/tags/$TAG_NAME --format='%(contents)' | head -n 1)

          # fallback if lightweight tag (no message)
          if [ -z "$TAG_MESSAGE" ]; then
            TAG_MESSAGE="$TAG_NAME"
          fi
          
          echo "message=$TAG_MESSAGE" >> $GITHUB_OUTPUT
          

      - name: Generate release notes
        run: |
          # get last tag, fallback to first commit if no tag exists
          # last tag or first commit
          LAST_TAG=$(git tag --sort=-creatordate | sed -n '2p')
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          LATEST_COMMIT=$(git rev-parse HEAD)
          
          # base repo url
          REPO_URL=${{github.server_url}}/${{ github.repository }}
  
          # create changelog file
          echo "## New Features\n\n\n## Changelog" > CHANGELOG.txt
          # generate actual release notes
          git log $LAST_TAG..HEAD \
            --pretty=format:"[\`%h\`]($REPO_URL/commit/%H) - %s" \
            >> CHANGELOG.txt
          
          # add link full link to commits
          COMPARE_START=${LAST_TAG:-$FIRST_COMMIT}
          echo "Full log: $REPO_URL/compare/$COMPARE_START..$LATEST_COMMIT" >> CHANGELOG.txt

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            download/*.jar
          body_path: CHANGELOG.txt
          draft: true
          name: ${{ steps.tagmsg.outputs.message }}
